package common;

public enum Type {
	CONNECT,
	REGISTER,
	LOGIN,
	TEXT,
	LOGOUT,
	GET_CATALOG,
    LIST_COURSES, 
    ENROLL_COURSE_STUDENT,
    ENROLL_COURSE,
    DROP_COURSE, 
    VIEW_BALANCE, 
    PAY_BALANCE,
    PROFILE,
    CREATE_COURSE,
    REMOVE_COURSE,
    REMOVE_STUDENT,
    ADD_HOLD,
    REMOVE_HOLD,
    VIEW_STUDENTS,
    REPORT,
    CLEAR_HOLD
}
